In [2]:
import numpy as np
import time

In [3]:
size = 100_00_000
py_list = list(range(size))
start = time.time()
sq_py= [x**2 for x in py_list]
end=time.time()
print(f"python list time = {end-start} seconds")
np_arr=np.array(py_list)
start = time.time()
sq_array=np_arr**2
end=time.time()
print(f"numpy array time = {end-start} seconds")

python list time = 0.96744704246521 seconds
numpy array time = 0.07518124580383301 seconds


In [4]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(arr2D.shape)

(3, 3)


In [6]:
arr1=np.zeros((2,3) , dtype="int64")
print(arr1)

[[0 0 0]
 [0 0 0]]


In [7]:
arr2= np.full((3,4),100)

In [8]:
print(arr2)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]


In [9]:
arr3=np.eye(5)
print(arr3)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
arr4=np.arange(0,11)
print(arr4)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [11]:
np.linspace(1,99,7)

array([ 1.        , 17.33333333, 33.66666667, 50.        , 66.33333333,
       82.66666667, 99.        ])

In [15]:
print([1,2,3])

[1, 2, 3]


In [ ]:
print(arr4[arr4>4])

In [ ]:
print(arr4[1:6])

In [13]:
Arro = np.array([1,2,3,4])
print(Arro.dtype)

int64


In [ ]:
arr3d = 