In [4]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
arr = np.array([1, 2, 3, 4])  
print(arr, type(arr))  
arr2 = np.array([1, 2, 3, 4, "prime", 3.14])  
print(arr2, type(arr2))  
# 2D Arrays - Matrix  
arr3 = np.array([[1, 2, 3], [4, 5, 6]])  
print(arr3, arr3.shape)

[1 2 3 4] <class 'numpy.ndarray'>
['1' '2' '3' '4' 'prime' '3.14'] <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]] (2, 3)


In [7]:
arr1=np.zeros((2,2))
print(arr1)
arr2=np.ones((3,3))
print(arr2)
arr3=np.full((2,2),2)
print(arr3)
arr4=np.eye(3)
print(arr4)
arr5=np.arange(1,20,2)
print(arr5)
arr6=np.linspace(0,10,17)
print(arr6)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 1  3  5  7  9 11 13 15 17 19]
[ 0.     0.625  1.25   1.875  2.5    3.125  3.75   4.375  5.     5.625
  6.25   6.875  7.5    8.125  8.75   9.375 10.   ]


In [8]:
np_arr=np.array([1,2,3,4,5,6,7,8])
view_arr=np_arr[1:4]
print(np_arr)
print(view_arr)

[1 2 3 4 5 6 7 8]
[2 3 4]


In [9]:
view_arr[0]=5

In [10]:
print(np_arr)

[1 5 3 4 5 6 7 8]


In [11]:
arr_nikki=np_arr**2

In [12]:
print(arr_nikki)

[ 1 25  9 16 25 36 49 64]


In [13]:
print(np.mean(arr_nikki))

28.125


In [14]:
print(np.median(arr_nikki))

25.0


In [15]:
print(np.std(arr_nikki))

19.534824672875875


In [16]:
print(np.var(arr_nikki))

381.609375


In [17]:
import pandas as pd

In [18]:
df=pd.DataFrame({
    "Name" : ["Alice" , "Bob"],
    "Cgpa" : [9.5,8.7]
})

In [19]:
df

Name  Cgpa
0  Alice   9.5
1    Bob   8.7

In [20]:
s=pd.Series([1,2,3],index=["Adam","Eve","Charlie"])

In [21]:
s1 = pd.Series([1, 2, 3])  
s2 = pd.Series([4, 5, 6]) 
print(s1 + s2) 

0    5
1    7
2    9
dtype: int64


In [22]:
s = pd.Series([1, 2, 3, 4, 5])  
s[0] = 100  
print(s)  
changed_s = s.drop(1)  
print(changed_s)  
print(s) 

0    100
1      2
2      3
3      4
4      5
dtype: int64
0    100
2      3
3      4
4      5
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64


In [23]:
np_arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
df=pd.DataFrame(np_arr,columns=["col1","col2","col3"])
print(df)

   col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9


In [24]:
df.head()

col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9

In [25]:
df.tail()

col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9

In [26]:
df.sample()

col1  col2  col3
1     4     5     6

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    3 non-null      int64
 1   col2    3 non-null      int64
 2   col3    3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes


In [28]:
df.describe()

col1  col2  col3
count   3.0   3.0   3.0
mean    4.0   5.0   6.0
std     3.0   3.0   3.0
min     1.0   2.0   3.0
25%     2.5   3.5   4.5
50%     4.0   5.0   6.0
75%     5.5   6.5   7.5
max     7.0   8.0   9.0

In [29]:
df.shape

(3, 3)

In [30]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [31]:
df.dtypes

col1    int64
col2    int64
col3    int64
dtype: object

In [32]:
df.loc[0]

col1    1
col2    2
col3    3
Name: 0, dtype: int64

In [33]:
df.loc[0:]

col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9

In [34]:
data = {  
'Name': ['Aarav', 'Isha', 'Rohan', 'Sneha', 'Vikram'],  
'Age': [25, 30, 35, 40, 45],  
'City': ['Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 'Chennai']  
}  
df = pd.DataFrame(data) 

In [35]:
print(df.at[0, "City"])  
print(df.iat[0, 2]) 

Delhi
Delhi


In [47]:
print(df) 
print(df.query("Age>10 and Name=='Isha'"))

     Name  Age       City
0   Aarav   25      Delhi
1    Isha   30     Mumbai
2   Rohan   35  Bangalore
3   Sneha   40    Kolkata
4  Vikram   45    Chennai
   Name  Age    City
1  Isha   30  Mumbai
